package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Awards generated by hbm2java
 */
public class Awards  implements java.io.Serializable {


     private int idAwards;
     private String name;
     private Date date;
     private String status;

    public Awards() {
    }

	
    public Awards(int idAwards) {
        this.idAwards = idAwards;
    }
    public Awards(int idAwards, String name, Date date, String status) {
       this.idAwards = idAwards;
       this.name = name;
       this.date = date;
       this.status = status;
    }
   
    public int getIdAwards() {
        return this.idAwards;
    }
    
    public void setIdAwards(int idAwards) {
        this.idAwards = idAwards;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


