package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1



/**
 * CartHasPCatergory generated by hbm2java
 */
public class CartHasPCatergory  implements java.io.Serializable {


     private CartHasPCatergoryId id;
     private Cart cart;
     private PCatergory PCatergory;
     private Integer qty;
     private Integer ptotal;

    public CartHasPCatergory() {
    }

	
    public CartHasPCatergory(CartHasPCatergoryId id, Cart cart, PCatergory PCatergory) {
        this.id = id;
        this.cart = cart;
        this.PCatergory = PCatergory;
    }
    public CartHasPCatergory(CartHasPCatergoryId id, Cart cart, PCatergory PCatergory, Integer qty, Integer ptotal) {
       this.id = id;
       this.cart = cart;
       this.PCatergory = PCatergory;
       this.qty = qty;
       this.ptotal = ptotal;
    }
   
    public CartHasPCatergoryId getId() {
        return this.id;
    }
    
    public void setId(CartHasPCatergoryId id) {
        this.id = id;
    }
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }
    public PCatergory getPCatergory() {
        return this.PCatergory;
    }
    
    public void setPCatergory(PCatergory PCatergory) {
        this.PCatergory = PCatergory;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Integer getPtotal() {
        return this.ptotal;
    }
    
    public void setPtotal(Integer ptotal) {
        this.ptotal = ptotal;
    }




}


