package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1



/**
 * CartHasProductsId generated by hbm2java
 */
public class CartHasProductsId  implements java.io.Serializable {


     private int cartIdCart;
     private int productsIdProducts;

    public CartHasProductsId() {
    }

    public CartHasProductsId(int cartIdCart, int productsIdProducts) {
       this.cartIdCart = cartIdCart;
       this.productsIdProducts = productsIdProducts;
    }
   
    public int getCartIdCart() {
        return this.cartIdCart;
    }
    
    public void setCartIdCart(int cartIdCart) {
        this.cartIdCart = cartIdCart;
    }
    public int getProductsIdProducts() {
        return this.productsIdProducts;
    }
    
    public void setProductsIdProducts(int productsIdProducts) {
        this.productsIdProducts = productsIdProducts;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CartHasProductsId) ) return false;
		 CartHasProductsId castOther = ( CartHasProductsId ) other; 
         
		 return (this.getCartIdCart()==castOther.getCartIdCart())
 && (this.getProductsIdProducts()==castOther.getProductsIdProducts());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCartIdCart();
         result = 37 * result + this.getProductsIdProducts();
         return result;
   }   


}


