package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Dispatchorders generated by hbm2java
 */
public class Dispatchorders  implements java.io.Serializable {


     private Integer idDispatchOrders;
     private Ordering ordering;
     private Date date;
     private Date time;
     private String status;
     private String cusComent;
     private Set<Productreview> productreviews = new HashSet<Productreview>(0);
     private Set<Returnorder> returnorders = new HashSet<Returnorder>(0);

    public Dispatchorders() {
    }

	
    public Dispatchorders(Ordering ordering) {
        this.ordering = ordering;
    }
    public Dispatchorders(Ordering ordering, Date date, Date time, String status, String cusComent, Set<Productreview> productreviews, Set<Returnorder> returnorders) {
       this.ordering = ordering;
       this.date = date;
       this.time = time;
       this.status = status;
       this.cusComent = cusComent;
       this.productreviews = productreviews;
       this.returnorders = returnorders;
    }
   
    public Integer getIdDispatchOrders() {
        return this.idDispatchOrders;
    }
    
    public void setIdDispatchOrders(Integer idDispatchOrders) {
        this.idDispatchOrders = idDispatchOrders;
    }
    public Ordering getOrdering() {
        return this.ordering;
    }
    
    public void setOrdering(Ordering ordering) {
        this.ordering = ordering;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getCusComent() {
        return this.cusComent;
    }
    
    public void setCusComent(String cusComent) {
        this.cusComent = cusComent;
    }
    public Set<Productreview> getProductreviews() {
        return this.productreviews;
    }
    
    public void setProductreviews(Set<Productreview> productreviews) {
        this.productreviews = productreviews;
    }
    public Set<Returnorder> getReturnorders() {
        return this.returnorders;
    }
    
    public void setReturnorders(Set<Returnorder> returnorders) {
        this.returnorders = returnorders;
    }




}


