package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer idInvoice;
     private User user;
     private Double total;
     private Date date;
     private Set<Ordering> orderings = new HashSet<Ordering>(0);
     private Set<InvoiceHasGrnHasProducts> invoiceHasGrnHasProductses = new HashSet<InvoiceHasGrnHasProducts>(0);

    public Invoice() {
    }

	
    public Invoice(User user) {
        this.user = user;
    }
    public Invoice(User user, Double total, Date date, Set<Ordering> orderings, Set<InvoiceHasGrnHasProducts> invoiceHasGrnHasProductses) {
       this.user = user;
       this.total = total;
       this.date = date;
       this.orderings = orderings;
       this.invoiceHasGrnHasProductses = invoiceHasGrnHasProductses;
    }
   
    public Integer getIdInvoice() {
        return this.idInvoice;
    }
    
    public void setIdInvoice(Integer idInvoice) {
        this.idInvoice = idInvoice;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set<Ordering> getOrderings() {
        return this.orderings;
    }
    
    public void setOrderings(Set<Ordering> orderings) {
        this.orderings = orderings;
    }
    public Set<InvoiceHasGrnHasProducts> getInvoiceHasGrnHasProductses() {
        return this.invoiceHasGrnHasProductses;
    }
    
    public void setInvoiceHasGrnHasProductses(Set<InvoiceHasGrnHasProducts> invoiceHasGrnHasProductses) {
        this.invoiceHasGrnHasProductses = invoiceHasGrnHasProductses;
    }




}


