package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1



/**
 * LoginActivity generated by hbm2java
 */
public class LoginActivity  implements java.io.Serializable {


     private Integer idLoginActivity;
     private Logintimes logintimes;
     private String description;
     private String status;

    public LoginActivity() {
    }

	
    public LoginActivity(Logintimes logintimes) {
        this.logintimes = logintimes;
    }
    public LoginActivity(Logintimes logintimes, String description, String status) {
       this.logintimes = logintimes;
       this.description = description;
       this.status = status;
    }
   
    public Integer getIdLoginActivity() {
        return this.idLoginActivity;
    }
    
    public void setIdLoginActivity(Integer idLoginActivity) {
        this.idLoginActivity = idLoginActivity;
    }
    public Logintimes getLogintimes() {
        return this.logintimes;
    }
    
    public void setLogintimes(Logintimes logintimes) {
        this.logintimes = logintimes;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


