package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private Integer idLogin;
     private User user;
     private String username;
     private String password;
     private String status;
     private Set<Logintimes> logintimeses = new HashSet<Logintimes>(0);

    public Login() {
    }

	
    public Login(User user) {
        this.user = user;
    }
    public Login(User user, String username, String password, String status, Set<Logintimes> logintimeses) {
       this.user = user;
       this.username = username;
       this.password = password;
       this.status = status;
       this.logintimeses = logintimeses;
    }
   
    public Integer getIdLogin() {
        return this.idLogin;
    }
    
    public void setIdLogin(Integer idLogin) {
        this.idLogin = idLogin;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<Logintimes> getLogintimeses() {
        return this.logintimeses;
    }
    
    public void setLogintimeses(Set<Logintimes> logintimeses) {
        this.logintimeses = logintimeses;
    }




}


