package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Logintimes generated by hbm2java
 */
public class Logintimes  implements java.io.Serializable {


     private Integer idLoginTimes;
     private Login login;
     private Date logdate;
     private Date intime;
     private Date outtime;
     private String status;
     private Set<LoginActivity> loginActivities = new HashSet<LoginActivity>(0);
     private Set<LogintimesHasPage> logintimesHasPages = new HashSet<LogintimesHasPage>(0);

    public Logintimes() {
    }

	
    public Logintimes(Login login) {
        this.login = login;
    }
    public Logintimes(Login login, Date logdate, Date intime, Date outtime, String status, Set<LoginActivity> loginActivities, Set<LogintimesHasPage> logintimesHasPages) {
       this.login = login;
       this.logdate = logdate;
       this.intime = intime;
       this.outtime = outtime;
       this.status = status;
       this.loginActivities = loginActivities;
       this.logintimesHasPages = logintimesHasPages;
    }
   
    public Integer getIdLoginTimes() {
        return this.idLoginTimes;
    }
    
    public void setIdLoginTimes(Integer idLoginTimes) {
        this.idLoginTimes = idLoginTimes;
    }
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }
    public Date getLogdate() {
        return this.logdate;
    }
    
    public void setLogdate(Date logdate) {
        this.logdate = logdate;
    }
    public Date getIntime() {
        return this.intime;
    }
    
    public void setIntime(Date intime) {
        this.intime = intime;
    }
    public Date getOuttime() {
        return this.outtime;
    }
    
    public void setOuttime(Date outtime) {
        this.outtime = outtime;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<LoginActivity> getLoginActivities() {
        return this.loginActivities;
    }
    
    public void setLoginActivities(Set<LoginActivity> loginActivities) {
        this.loginActivities = loginActivities;
    }
    public Set<LogintimesHasPage> getLogintimesHasPages() {
        return this.logintimesHasPages;
    }
    
    public void setLogintimesHasPages(Set<LogintimesHasPage> logintimesHasPages) {
        this.logintimesHasPages = logintimesHasPages;
    }




}


