package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Messages generated by hbm2java
 */
public class Messages  implements java.io.Serializable {


     private Integer idMessages;
     private User user;
     private String heding;
     private String mbody;
     private String status;
     private Date mdate;
     private Date mtime;
     private String reply;

    public Messages() {
    }

	
    public Messages(User user) {
        this.user = user;
    }
    public Messages(User user, String heding, String mbody, String status, Date mdate, Date mtime, String reply) {
       this.user = user;
       this.heding = heding;
       this.mbody = mbody;
       this.status = status;
       this.mdate = mdate;
       this.mtime = mtime;
       this.reply = reply;
    }
   
    public Integer getIdMessages() {
        return this.idMessages;
    }
    
    public void setIdMessages(Integer idMessages) {
        this.idMessages = idMessages;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getHeding() {
        return this.heding;
    }
    
    public void setHeding(String heding) {
        this.heding = heding;
    }
    public String getMbody() {
        return this.mbody;
    }
    
    public void setMbody(String mbody) {
        this.mbody = mbody;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getMdate() {
        return this.mdate;
    }
    
    public void setMdate(Date mdate) {
        this.mdate = mdate;
    }
    public Date getMtime() {
        return this.mtime;
    }
    
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }
    public String getReply() {
        return this.reply;
    }
    
    public void setReply(String reply) {
        this.reply = reply;
    }




}


