package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * News generated by hbm2java
 */
public class News  implements java.io.Serializable {


     private int idNews;
     private String newshedder;
     private String newsbody;
     private Date viewDate;
     private String status;

    public News() {
    }

	
    public News(int idNews) {
        this.idNews = idNews;
    }
    public News(int idNews, String newshedder, String newsbody, Date viewDate, String status) {
       this.idNews = idNews;
       this.newshedder = newshedder;
       this.newsbody = newsbody;
       this.viewDate = viewDate;
       this.status = status;
    }
   
    public int getIdNews() {
        return this.idNews;
    }
    
    public void setIdNews(int idNews) {
        this.idNews = idNews;
    }
    public String getNewshedder() {
        return this.newshedder;
    }
    
    public void setNewshedder(String newshedder) {
        this.newshedder = newshedder;
    }
    public String getNewsbody() {
        return this.newsbody;
    }
    
    public void setNewsbody(String newsbody) {
        this.newsbody = newsbody;
    }
    public Date getViewDate() {
        return this.viewDate;
    }
    
    public void setViewDate(Date viewDate) {
        this.viewDate = viewDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


