package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Notifications generated by hbm2java
 */
public class Notifications  implements java.io.Serializable {


     private Integer idNotifications;
     private User user;
     private Date adddate;
     private String title;
     private String status;

    public Notifications() {
    }

	
    public Notifications(User user) {
        this.user = user;
    }
    public Notifications(User user, Date adddate, String title, String status) {
       this.user = user;
       this.adddate = adddate;
       this.title = title;
       this.status = status;
    }
   
    public Integer getIdNotifications() {
        return this.idNotifications;
    }
    
    public void setIdNotifications(Integer idNotifications) {
        this.idNotifications = idNotifications;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getAdddate() {
        return this.adddate;
    }
    
    public void setAdddate(Date adddate) {
        this.adddate = adddate;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


