package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Page generated by hbm2java
 */
public class Page  implements java.io.Serializable {


     private Integer idPage;
     private String name;
     private String url;
     private Set<UsertypeHasPage> usertypeHasPages = new HashSet<UsertypeHasPage>(0);
     private Set<LogintimesHasPage> logintimesHasPages = new HashSet<LogintimesHasPage>(0);

    public Page() {
    }

    public Page(String name, String url, Set<UsertypeHasPage> usertypeHasPages, Set<LogintimesHasPage> logintimesHasPages) {
       this.name = name;
       this.url = url;
       this.usertypeHasPages = usertypeHasPages;
       this.logintimesHasPages = logintimesHasPages;
    }
   
    public Integer getIdPage() {
        return this.idPage;
    }
    
    public void setIdPage(Integer idPage) {
        this.idPage = idPage;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Set<UsertypeHasPage> getUsertypeHasPages() {
        return this.usertypeHasPages;
    }
    
    public void setUsertypeHasPages(Set<UsertypeHasPage> usertypeHasPages) {
        this.usertypeHasPages = usertypeHasPages;
    }
    public Set<LogintimesHasPage> getLogintimesHasPages() {
        return this.logintimesHasPages;
    }
    
    public void setLogintimesHasPages(Set<LogintimesHasPage> logintimesHasPages) {
        this.logintimesHasPages = logintimesHasPages;
    }




}


