package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PCatergory generated by hbm2java
 */
public class PCatergory  implements java.io.Serializable {


     private Integer idPCatergory;
     private Shipping shipping;
     private String catName;
     private String status;
     private Set<Products> productses = new HashSet<Products>(0);
     private Set<CartHasPCatergory> cartHasPCatergories = new HashSet<CartHasPCatergory>(0);

    public PCatergory() {
    }

	
    public PCatergory(Shipping shipping) {
        this.shipping = shipping;
    }
    public PCatergory(Shipping shipping, String catName, String status, Set<Products> productses, Set<CartHasPCatergory> cartHasPCatergories) {
       this.shipping = shipping;
       this.catName = catName;
       this.status = status;
       this.productses = productses;
       this.cartHasPCatergories = cartHasPCatergories;
    }
   
    public Integer getIdPCatergory() {
        return this.idPCatergory;
    }
    
    public void setIdPCatergory(Integer idPCatergory) {
        this.idPCatergory = idPCatergory;
    }
    public Shipping getShipping() {
        return this.shipping;
    }
    
    public void setShipping(Shipping shipping) {
        this.shipping = shipping;
    }
    public String getCatName() {
        return this.catName;
    }
    
    public void setCatName(String catName) {
        this.catName = catName;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<Products> getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set<Products> productses) {
        this.productses = productses;
    }
    public Set<CartHasPCatergory> getCartHasPCatergories() {
        return this.cartHasPCatergories;
    }
    
    public void setCartHasPCatergories(Set<CartHasPCatergory> cartHasPCatergories) {
        this.cartHasPCatergories = cartHasPCatergories;
    }




}


