package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1



/**
 * ProductsHasSupplier generated by hbm2java
 */
public class ProductsHasSupplier  implements java.io.Serializable {


     private Integer idGrn;
     private int productsIdProducts;
     private int supplierIdSupplier;

    public ProductsHasSupplier() {
    }

    public ProductsHasSupplier(int productsIdProducts, int supplierIdSupplier) {
       this.productsIdProducts = productsIdProducts;
       this.supplierIdSupplier = supplierIdSupplier;
    }
   
    public Integer getIdGrn() {
        return this.idGrn;
    }
    
    public void setIdGrn(Integer idGrn) {
        this.idGrn = idGrn;
    }
    public int getProductsIdProducts() {
        return this.productsIdProducts;
    }
    
    public void setProductsIdProducts(int productsIdProducts) {
        this.productsIdProducts = productsIdProducts;
    }
    public int getSupplierIdSupplier() {
        return this.supplierIdSupplier;
    }
    
    public void setSupplierIdSupplier(int supplierIdSupplier) {
        this.supplierIdSupplier = supplierIdSupplier;
    }




}


