package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1



/**
 * ProductsHasBrands generated by hbm2java
 */
public class ProductsHasBrands  implements java.io.Serializable {


     private Integer idProductBrand;
     private Brands brands;
     private Products products;
     private Double rating;
     private String status;

    public ProductsHasBrands() {
    }

	
    public ProductsHasBrands(Brands brands, Products products) {
        this.brands = brands;
        this.products = products;
    }
    public ProductsHasBrands(Brands brands, Products products, Double rating, String status) {
       this.brands = brands;
       this.products = products;
       this.rating = rating;
       this.status = status;
    }
   
    public Integer getIdProductBrand() {
        return this.idProductBrand;
    }
    
    public void setIdProductBrand(Integer idProductBrand) {
        this.idProductBrand = idProductBrand;
    }
    public Brands getBrands() {
        return this.brands;
    }
    
    public void setBrands(Brands brands) {
        this.brands = brands;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Double getRating() {
        return this.rating;
    }
    
    public void setRating(Double rating) {
        this.rating = rating;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


