package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Productreview generated by hbm2java
 */
public class Productreview  implements java.io.Serializable {


     private Integer idProductReview;
     private Dispatchorders dispatchorders;
     private Products products;
     private User user;
     private String review;
     private Date reviewDate;
     private String status;

    public Productreview() {
    }

	
    public Productreview(Dispatchorders dispatchorders, Products products, User user) {
        this.dispatchorders = dispatchorders;
        this.products = products;
        this.user = user;
    }
    public Productreview(Dispatchorders dispatchorders, Products products, User user, String review, Date reviewDate, String status) {
       this.dispatchorders = dispatchorders;
       this.products = products;
       this.user = user;
       this.review = review;
       this.reviewDate = reviewDate;
       this.status = status;
    }
   
    public Integer getIdProductReview() {
        return this.idProductReview;
    }
    
    public void setIdProductReview(Integer idProductReview) {
        this.idProductReview = idProductReview;
    }
    public Dispatchorders getDispatchorders() {
        return this.dispatchorders;
    }
    
    public void setDispatchorders(Dispatchorders dispatchorders) {
        this.dispatchorders = dispatchorders;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getReview() {
        return this.review;
    }
    
    public void setReview(String review) {
        this.review = review;
    }
    public Date getReviewDate() {
        return this.reviewDate;
    }
    
    public void setReviewDate(Date reviewDate) {
        this.reviewDate = reviewDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


