package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Productoffers generated by hbm2java
 */
public class Productoffers  implements java.io.Serializable {


     private Integer idProductOffers;
     private GrnHasProducts grnHasProducts;
     private Integer presentage;
     private Date dateofview;
     private String offerstatus;
     private Integer offerqty;
     private String datestatus;
     private Date dateofadded;

    public Productoffers() {
    }

	
    public Productoffers(GrnHasProducts grnHasProducts) {
        this.grnHasProducts = grnHasProducts;
    }
    public Productoffers(GrnHasProducts grnHasProducts, Integer presentage, Date dateofview, String offerstatus, Integer offerqty, String datestatus, Date dateofadded) {
       this.grnHasProducts = grnHasProducts;
       this.presentage = presentage;
       this.dateofview = dateofview;
       this.offerstatus = offerstatus;
       this.offerqty = offerqty;
       this.datestatus = datestatus;
       this.dateofadded = dateofadded;
    }
   
    public Integer getIdProductOffers() {
        return this.idProductOffers;
    }
    
    public void setIdProductOffers(Integer idProductOffers) {
        this.idProductOffers = idProductOffers;
    }
    public GrnHasProducts getGrnHasProducts() {
        return this.grnHasProducts;
    }
    
    public void setGrnHasProducts(GrnHasProducts grnHasProducts) {
        this.grnHasProducts = grnHasProducts;
    }
    public Integer getPresentage() {
        return this.presentage;
    }
    
    public void setPresentage(Integer presentage) {
        this.presentage = presentage;
    }
    public Date getDateofview() {
        return this.dateofview;
    }
    
    public void setDateofview(Date dateofview) {
        this.dateofview = dateofview;
    }
    public String getOfferstatus() {
        return this.offerstatus;
    }
    
    public void setOfferstatus(String offerstatus) {
        this.offerstatus = offerstatus;
    }
    public Integer getOfferqty() {
        return this.offerqty;
    }
    
    public void setOfferqty(Integer offerqty) {
        this.offerqty = offerqty;
    }
    public String getDatestatus() {
        return this.datestatus;
    }
    
    public void setDatestatus(String datestatus) {
        this.datestatus = datestatus;
    }
    public Date getDateofadded() {
        return this.dateofadded;
    }
    
    public void setDateofadded(Date dateofadded) {
        this.dateofadded = dateofadded;
    }




}


