package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private Integer idProducts;
     private PCatergory PCatergory;
     private String productName;
     private String description;
     private String img;
     private Integer tolQty;
     private Integer status;
     private Set<Productreview> productreviews = new HashSet<Productreview>(0);
     private Set<UserHasProductsReview> userHasProductsReviews = new HashSet<UserHasProductsReview>(0);
     private Set<CartHasProducts> cartHasProductses = new HashSet<CartHasProducts>(0);
     private Set<Ratings> ratingses = new HashSet<Ratings>(0);
     private Set<Productselling> productsellings = new HashSet<Productselling>(0);
     private Set<ProductsHasBrands> productsHasBrandses = new HashSet<ProductsHasBrands>(0);
     private Set<GrnHasProducts> grnHasProductses = new HashSet<GrnHasProducts>(0);

    public Products() {
    }

	
    public Products(PCatergory PCatergory) {
        this.PCatergory = PCatergory;
    }
    public Products(PCatergory PCatergory, String productName, String description, String img, Integer tolQty, Integer status, Set<Productreview> productreviews, Set<UserHasProductsReview> userHasProductsReviews, Set<CartHasProducts> cartHasProductses, Set<Ratings> ratingses, Set<Productselling> productsellings, Set<ProductsHasBrands> productsHasBrandses, Set<GrnHasProducts> grnHasProductses) {
       this.PCatergory = PCatergory;
       this.productName = productName;
       this.description = description;
       this.img = img;
       this.tolQty = tolQty;
       this.status = status;
       this.productreviews = productreviews;
       this.userHasProductsReviews = userHasProductsReviews;
       this.cartHasProductses = cartHasProductses;
       this.ratingses = ratingses;
       this.productsellings = productsellings;
       this.productsHasBrandses = productsHasBrandses;
       this.grnHasProductses = grnHasProductses;
    }
   
    public Integer getIdProducts() {
        return this.idProducts;
    }
    
    public void setIdProducts(Integer idProducts) {
        this.idProducts = idProducts;
    }
    public PCatergory getPCatergory() {
        return this.PCatergory;
    }
    
    public void setPCatergory(PCatergory PCatergory) {
        this.PCatergory = PCatergory;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }
    public Integer getTolQty() {
        return this.tolQty;
    }
    
    public void setTolQty(Integer tolQty) {
        this.tolQty = tolQty;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set<Productreview> getProductreviews() {
        return this.productreviews;
    }
    
    public void setProductreviews(Set<Productreview> productreviews) {
        this.productreviews = productreviews;
    }
    public Set<UserHasProductsReview> getUserHasProductsReviews() {
        return this.userHasProductsReviews;
    }
    
    public void setUserHasProductsReviews(Set<UserHasProductsReview> userHasProductsReviews) {
        this.userHasProductsReviews = userHasProductsReviews;
    }
    public Set<CartHasProducts> getCartHasProductses() {
        return this.cartHasProductses;
    }
    
    public void setCartHasProductses(Set<CartHasProducts> cartHasProductses) {
        this.cartHasProductses = cartHasProductses;
    }
    public Set<Ratings> getRatingses() {
        return this.ratingses;
    }
    
    public void setRatingses(Set<Ratings> ratingses) {
        this.ratingses = ratingses;
    }
    public Set<Productselling> getProductsellings() {
        return this.productsellings;
    }
    
    public void setProductsellings(Set<Productselling> productsellings) {
        this.productsellings = productsellings;
    }
    public Set<ProductsHasBrands> getProductsHasBrandses() {
        return this.productsHasBrandses;
    }
    
    public void setProductsHasBrandses(Set<ProductsHasBrands> productsHasBrandses) {
        this.productsHasBrandses = productsHasBrandses;
    }
    public Set<GrnHasProducts> getGrnHasProductses() {
        return this.grnHasProductses;
    }
    
    public void setGrnHasProductses(Set<GrnHasProducts> grnHasProductses) {
        this.grnHasProductses = grnHasProductses;
    }




}


