package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Shipping generated by hbm2java
 */
public class Shipping  implements java.io.Serializable {


     private Integer idShipping;
     private String mthodName;
     private String cost;
     private String vehicleType;
     private Set<PCatergory> PCatergories = new HashSet<PCatergory>(0);

    public Shipping() {
    }

    public Shipping(String mthodName, String cost, String vehicleType, Set<PCatergory> PCatergories) {
       this.mthodName = mthodName;
       this.cost = cost;
       this.vehicleType = vehicleType;
       this.PCatergories = PCatergories;
    }
   
    public Integer getIdShipping() {
        return this.idShipping;
    }
    
    public void setIdShipping(Integer idShipping) {
        this.idShipping = idShipping;
    }
    public String getMthodName() {
        return this.mthodName;
    }
    
    public void setMthodName(String mthodName) {
        this.mthodName = mthodName;
    }
    public String getCost() {
        return this.cost;
    }
    
    public void setCost(String cost) {
        this.cost = cost;
    }
    public String getVehicleType() {
        return this.vehicleType;
    }
    
    public void setVehicleType(String vehicleType) {
        this.vehicleType = vehicleType;
    }
    public Set<PCatergory> getPCatergories() {
        return this.PCatergories;
    }
    
    public void setPCatergories(Set<PCatergory> PCatergories) {
        this.PCatergories = PCatergories;
    }




}


