package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Supplier generated by hbm2java
 */
public class Supplier  implements java.io.Serializable {


     private Integer idSupplier;
     private Company company;
     private String fullName;
     private String street1;
     private String street2;
     private String city;
     private String pcode;
     private String tel;
     private String email;
     private String webSite;
     private int supplierRequestIdSupplierRequest;
     private Double ratings;
     private String status;
     private Date joinDate;
     private Set<Grn> grns = new HashSet<Grn>(0);

    public Supplier() {
    }

	
    public Supplier(Company company, int supplierRequestIdSupplierRequest) {
        this.company = company;
        this.supplierRequestIdSupplierRequest = supplierRequestIdSupplierRequest;
    }
    public Supplier(Company company, String fullName, String street1, String street2, String city, String pcode, String tel, String email, String webSite, int supplierRequestIdSupplierRequest, Double ratings, String status, Date joinDate, Set<Grn> grns) {
       this.company = company;
       this.fullName = fullName;
       this.street1 = street1;
       this.street2 = street2;
       this.city = city;
       this.pcode = pcode;
       this.tel = tel;
       this.email = email;
       this.webSite = webSite;
       this.supplierRequestIdSupplierRequest = supplierRequestIdSupplierRequest;
       this.ratings = ratings;
       this.status = status;
       this.joinDate = joinDate;
       this.grns = grns;
    }
   
    public Integer getIdSupplier() {
        return this.idSupplier;
    }
    
    public void setIdSupplier(Integer idSupplier) {
        this.idSupplier = idSupplier;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getStreet1() {
        return this.street1;
    }
    
    public void setStreet1(String street1) {
        this.street1 = street1;
    }
    public String getStreet2() {
        return this.street2;
    }
    
    public void setStreet2(String street2) {
        this.street2 = street2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getPcode() {
        return this.pcode;
    }
    
    public void setPcode(String pcode) {
        this.pcode = pcode;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getWebSite() {
        return this.webSite;
    }
    
    public void setWebSite(String webSite) {
        this.webSite = webSite;
    }
    public int getSupplierRequestIdSupplierRequest() {
        return this.supplierRequestIdSupplierRequest;
    }
    
    public void setSupplierRequestIdSupplierRequest(int supplierRequestIdSupplierRequest) {
        this.supplierRequestIdSupplierRequest = supplierRequestIdSupplierRequest;
    }
    public Double getRatings() {
        return this.ratings;
    }
    
    public void setRatings(Double ratings) {
        this.ratings = ratings;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getJoinDate() {
        return this.joinDate;
    }
    
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }
    public Set<Grn> getGrns() {
        return this.grns;
    }
    
    public void setGrns(Set<Grn> grns) {
        this.grns = grns;
    }




}


