package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1



/**
 * UsertypeHasPage generated by hbm2java
 */
public class UsertypeHasPage  implements java.io.Serializable {


     private Integer idPhU;
     private Page page;
     private Usertype usertype;

    public UsertypeHasPage() {
    }

    public UsertypeHasPage(Page page, Usertype usertype) {
       this.page = page;
       this.usertype = usertype;
    }
   
    public Integer getIdPhU() {
        return this.idPhU;
    }
    
    public void setIdPhU(Integer idPhU) {
        this.idPhU = idPhU;
    }
    public Page getPage() {
        return this.page;
    }
    
    public void setPage(Page page) {
        this.page = page;
    }
    public Usertype getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(Usertype usertype) {
        this.usertype = usertype;
    }




}


