package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usertype generated by hbm2java
 */
public class Usertype  implements java.io.Serializable {


     private Integer idUserType;
     private String typeName;
     private String status;
     private Set<User> users = new HashSet<User>(0);
     private Set<UsertypeHasPage> usertypeHasPages = new HashSet<UsertypeHasPage>(0);

    public Usertype() {
    }

    public Usertype(String typeName, String status, Set<User> users, Set<UsertypeHasPage> usertypeHasPages) {
       this.typeName = typeName;
       this.status = status;
       this.users = users;
       this.usertypeHasPages = usertypeHasPages;
    }
   
    public Integer getIdUserType() {
        return this.idUserType;
    }
    
    public void setIdUserType(Integer idUserType) {
        this.idUserType = idUserType;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }
    public Set<UsertypeHasPage> getUsertypeHasPages() {
        return this.usertypeHasPages;
    }
    
    public void setUsertypeHasPages(Set<UsertypeHasPage> usertypeHasPages) {
        this.usertypeHasPages = usertypeHasPages;
    }




}


