package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer idUser;
     private Usertype usertype;
     private String fname;
     private String lname;
     private String email;
     private String tel;
     private Date signDate;
     private String uimg;
     private String status;
     private Set<Productreview> productreviews = new HashSet<Productreview>(0);
     private Set<Cart> carts = new HashSet<Cart>(0);
     private Set<Notifications> notificationses = new HashSet<Notifications>(0);
     private Set<Ratings> ratingses = new HashSet<Ratings>(0);
     private Set<Ordering> orderings = new HashSet<Ordering>(0);
     private Set<UserHasProductsReview> userHasProductsReviews = new HashSet<UserHasProductsReview>(0);
     private Set<Feedback> feedbacks = new HashSet<Feedback>(0);
     private Set<Wishlist> wishlists = new HashSet<Wishlist>(0);
     private Set<Invoice> invoices = new HashSet<Invoice>(0);
     private Set<Login> logins = new HashSet<Login>(0);
     private Set<Shippingorder> shippingorders = new HashSet<Shippingorder>(0);
     private Set<Messages> messageses = new HashSet<Messages>(0);

    public User() {
    }

	
    public User(Usertype usertype) {
        this.usertype = usertype;
    }
    public User(Usertype usertype, String fname, String lname, String email, String tel, Date signDate, String uimg, String status, Set<Productreview> productreviews, Set<Cart> carts, Set<Notifications> notificationses, Set<Ratings> ratingses, Set<Ordering> orderings, Set<UserHasProductsReview> userHasProductsReviews, Set<Feedback> feedbacks, Set<Wishlist> wishlists, Set<Invoice> invoices, Set<Login> logins, Set<Shippingorder> shippingorders, Set<Messages> messageses) {
       this.usertype = usertype;
       this.fname = fname;
       this.lname = lname;
       this.email = email;
       this.tel = tel;
       this.signDate = signDate;
       this.uimg = uimg;
       this.status = status;
       this.productreviews = productreviews;
       this.carts = carts;
       this.notificationses = notificationses;
       this.ratingses = ratingses;
       this.orderings = orderings;
       this.userHasProductsReviews = userHasProductsReviews;
       this.feedbacks = feedbacks;
       this.wishlists = wishlists;
       this.invoices = invoices;
       this.logins = logins;
       this.shippingorders = shippingorders;
       this.messageses = messageses;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public Usertype getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(Usertype usertype) {
        this.usertype = usertype;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public Date getSignDate() {
        return this.signDate;
    }
    
    public void setSignDate(Date signDate) {
        this.signDate = signDate;
    }
    public String getUimg() {
        return this.uimg;
    }
    
    public void setUimg(String uimg) {
        this.uimg = uimg;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<Productreview> getProductreviews() {
        return this.productreviews;
    }
    
    public void setProductreviews(Set<Productreview> productreviews) {
        this.productreviews = productreviews;
    }
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }
    public Set<Notifications> getNotificationses() {
        return this.notificationses;
    }
    
    public void setNotificationses(Set<Notifications> notificationses) {
        this.notificationses = notificationses;
    }
    public Set<Ratings> getRatingses() {
        return this.ratingses;
    }
    
    public void setRatingses(Set<Ratings> ratingses) {
        this.ratingses = ratingses;
    }
    public Set<Ordering> getOrderings() {
        return this.orderings;
    }
    
    public void setOrderings(Set<Ordering> orderings) {
        this.orderings = orderings;
    }
    public Set<UserHasProductsReview> getUserHasProductsReviews() {
        return this.userHasProductsReviews;
    }
    
    public void setUserHasProductsReviews(Set<UserHasProductsReview> userHasProductsReviews) {
        this.userHasProductsReviews = userHasProductsReviews;
    }
    public Set<Feedback> getFeedbacks() {
        return this.feedbacks;
    }
    
    public void setFeedbacks(Set<Feedback> feedbacks) {
        this.feedbacks = feedbacks;
    }
    public Set<Wishlist> getWishlists() {
        return this.wishlists;
    }
    
    public void setWishlists(Set<Wishlist> wishlists) {
        this.wishlists = wishlists;
    }
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }
    public Set<Login> getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set<Login> logins) {
        this.logins = logins;
    }
    public Set<Shippingorder> getShippingorders() {
        return this.shippingorders;
    }
    
    public void setShippingorders(Set<Shippingorder> shippingorders) {
        this.shippingorders = shippingorders;
    }
    public Set<Messages> getMessageses() {
        return this.messageses;
    }
    
    public void setMessageses(Set<Messages> messageses) {
        this.messageses = messageses;
    }




}


