package DB;
// Generated May 1, 2017 3:38:53 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * WishlistHasGrnHasProducts generated by hbm2java
 */
public class WishlistHasGrnHasProducts  implements java.io.Serializable {


     private Integer idwishlistHasGrnProducts;
     private GrnHasProducts grnHasProducts;
     private Wishlist wishlist;
     private Date wishAddDate;
     private Date wishAddTime;
     private String status;

    public WishlistHasGrnHasProducts() {
    }

	
    public WishlistHasGrnHasProducts(GrnHasProducts grnHasProducts, Wishlist wishlist) {
        this.grnHasProducts = grnHasProducts;
        this.wishlist = wishlist;
    }
    public WishlistHasGrnHasProducts(GrnHasProducts grnHasProducts, Wishlist wishlist, Date wishAddDate, Date wishAddTime, String status) {
       this.grnHasProducts = grnHasProducts;
       this.wishlist = wishlist;
       this.wishAddDate = wishAddDate;
       this.wishAddTime = wishAddTime;
       this.status = status;
    }
   
    public Integer getIdwishlistHasGrnProducts() {
        return this.idwishlistHasGrnProducts;
    }
    
    public void setIdwishlistHasGrnProducts(Integer idwishlistHasGrnProducts) {
        this.idwishlistHasGrnProducts = idwishlistHasGrnProducts;
    }
    public GrnHasProducts getGrnHasProducts() {
        return this.grnHasProducts;
    }
    
    public void setGrnHasProducts(GrnHasProducts grnHasProducts) {
        this.grnHasProducts = grnHasProducts;
    }
    public Wishlist getWishlist() {
        return this.wishlist;
    }
    
    public void setWishlist(Wishlist wishlist) {
        this.wishlist = wishlist;
    }
    public Date getWishAddDate() {
        return this.wishAddDate;
    }
    
    public void setWishAddDate(Date wishAddDate) {
        this.wishAddDate = wishAddDate;
    }
    public Date getWishAddTime() {
        return this.wishAddTime;
    }
    
    public void setWishAddTime(Date wishAddTime) {
        this.wishAddTime = wishAddTime;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


